-- V10__expandir_modelo_dominio_tenant.sql
-- Expansão de Clientes
ALTER TABLE clientes 
    ADD COLUMN IF NOT EXISTS tipo_pessoa VARCHAR(2) DEFAULT 'PJ',
    ADD COLUMN IF NOT EXISTS razao_social VARCHAR(255),
    ADD COLUMN IF NOT EXISTS inscricao_estadual VARCHAR(50),
    ADD COLUMN IF NOT EXISTS limite_credito NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS tabela_preco_padrao VARCHAR(50),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ATIVO',
    ADD COLUMN IF NOT EXISTS endereco JSONB;

-- Expansão de Fornecedores
ALTER TABLE fornecedores
    ADD COLUMN IF NOT EXISTS tipo_pessoa VARCHAR(2) DEFAULT 'PJ',
    ADD COLUMN IF NOT EXISTS razao_social VARCHAR(255),
    ADD COLUMN IF NOT EXISTS inscricao_estadual VARCHAR(50),
    ADD COLUMN IF NOT EXISTS categoria_fornecedor VARCHAR(100),
    ADD COLUMN IF NOT EXISTS prazo_pagamento_padrao INTEGER,
    ADD COLUMN IF NOT EXISTS contato_nome VARCHAR(255),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ATIVO',
    ADD COLUMN IF NOT EXISTS endereco JSONB;

-- Expansão de Materiais
ALTER TABLE materiais
    ADD COLUMN IF NOT EXISTS tipo_material VARCHAR(50),
    ADD COLUMN IF NOT EXISTS composicao VARCHAR(255),
    ADD COLUMN IF NOT EXISTS ncm VARCHAR(20),
    ADD COLUMN IF NOT EXISTS unidade_compra VARCHAR(20),
    ADD COLUMN IF NOT EXISTS fator_conversao NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS largura NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS gramatura NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS rendimento NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ATIVO',
    ADD COLUMN IF NOT EXISTS fornecedor_padrao_id UUID REFERENCES fornecedores(id);

-- Expansão de Produtos Base
ALTER TABLE produtos_base
    ADD COLUMN IF NOT EXISTS marca VARCHAR(100),
    ADD COLUMN IF NOT EXISTS categoria VARCHAR(100),
    ADD COLUMN IF NOT EXISTS colecao VARCHAR(100),
    ADD COLUMN IF NOT EXISTS genero VARCHAR(20),
    ADD COLUMN IF NOT EXISTS ncm VARCHAR(20),
    ADD COLUMN IF NOT EXISTS cest VARCHAR(20),
    ADD COLUMN IF NOT EXISTS origem VARCHAR(50),
    ADD COLUMN IF NOT EXISTS peso_bruto NUMERIC(10, 3),
    ADD COLUMN IF NOT EXISTS peso_liquido NUMERIC(10, 3),
    ADD COLUMN IF NOT EXISTS status VARCHAR(20) DEFAULT 'ATIVO';
